application: fluid-isotope-91910
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup).*
  script: scaffold.wsgi.application
  login: admin
  secure: always

- url: /static/admin/
  static_dir: sitepackages/django/contrib/admin/static/admin/
  secure: always

- url: /static/images
  static_dir: static/images

- url: /static/js
  static_dir: static/js

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: scaffold.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: scaffold.wsgi.application
  secure: always

libraries:
- name: PIL
  version: "1.1.7"

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/google_appengine*
    - \.storage.*
    - (.*)\.pyc
    - .git*
