#THIRD PARTY
from django import forms
from django.forms.extras.widgets import SelectDateWidget
#LOCAL
from .models import BlogPostVersion


class BlogPostForm(forms.ModelForm):
    """
    Form for adding a new BlogPost and BlogPostVersion.
    """
    #Blog Post fields added here. BlogPostVersion fields are generated by the modelform
    title = forms.CharField(max_length=500)
    slug = forms.CharField(max_length=100)

    class Meta:
        model = BlogPostVersion
        fields = ['copy','published']
        widgets = {'published': SelectDateWidget}